### ISSUE TITLE
Just curious: why waiting until completion to open source Gaffer2?

### ISSUE THREAD

**Issue by kfogel** [GovernmentCommunicationsHeadquarters/Gaffer#10]
Hi.  I'm just curious why you're waiting until Gaffer2 is completed before publishing it under an open source license.  Is there some reason not to do its development in the open?

(Serious question, not meant facetiously, in case that's not clear.  I can think of both good and bad reasons to wait, and wasn't sure which ones were operative here -- so I thought I'd just ask!)

**Comment by gaffer01** [comment]
Hi. Gaffer2 will not be complete when it is published - it will be a work in progress with plenty of room for further development.

**Comment by kfogel** [comment]
Thanks, @gaffer01.  What I was really asking is what is the publication boundary -- that is, given the above, why not do the work in an open repository starting from the beginning?

**Comment by foxx** [comment]
@kfogel Most likely because the code has to be fully audited before being released, to ensure nothing is being leaked out to the public, and also to protect themselves against negative press (e.g. dodgy commit messages, leaked info etc). Github promotes social development, but this is the exact opposite of how GCHQ work, at least from an external standpoint, instead they are using Github as a release mechanism, rather than a development workflow tool. Shame really.

**Comment by hitchcott** [comment]
Makes sense they have to audit stuff. Either way it's :+1: for open sourcing it in the first place.

**Comment by SamMorrowDrums** [comment]
@gaffer01 I hope you are thinking of ways you can move away from this simplistic publication model, and into a more collaborative mode. I understand it's all happening within an organisation that has thousands of internal barriers to collaboratively working on software in an open community, but without that mutual trust, you haven't built any trust, just gave us a tool, which is fine, but ultimately disappointing and not worthy of the same excitement that most other interesting OS projects command.

**Comment by kfogel** [comment]
Hmm.  There's a lot of speculation in this thread as to the reasons GCHQ isn't doing the work in the open in the first place.  Only @gaffer01 can say for sure which reasons are correct and which aren't, but if it were just a matter of code having to be audited before being published, the usual method for solving that -- a method that continues to work *after* publication -- is to have a dedicated branch for pre-audit code, and keep that branch only in internal repositories.  As soon as changes are approved, they can go to out to the public repository (on whatever branch is appropriate, presumably `master`).  Git makes this pretty easy; I have worked on projects that published to two repositories and it was fine.  One can set up hooks ("triggers" I guess git calls them) to make sure changes don't get published in the wrong repository just because someone made a typo when pushing, obviously.

@foxx and @SamMorrowDrums: As to whether GCHQ should be working more collaboratively, that's a separate question from publication, and I don't think we know enough to say whether they should be more collaborative or not.  It's not all upside, after all -- they might have good reasons for choosing one side of that tradeoff instead of the other.

More generally, I think there's often a mistaken impression that "open source" equals "collaborative development methodology".  The two don't always go together, and that's okay.  The only thing open source is definitely about is users' freedom to copy, customize, and redistribute the software as they see fit.  Whether a broadly collaborative development model makes sense for a particular project is a complicated question, and involves many more factors than just the license the software is under.

So I'm not making any assumptions about what reasons GCHQ has for not open-sourcing their code from Day One, nor about whether they should try for a more collaborative style of development.  However, I *am* emphasizing to @gaffer01 that one can put stuff in a public place starting from the earliest stages of development, without being under any obligation to change one's development methodology by taking on more collaborators.  While the latter would require the former, the former does **not** force the latter.

**Comment by gaffer01** [comment]
The Gaffer2 code is currently being tidied and reviewed before release. Once it has been released, further development will be done here. The hope is to be able to accept contributions from the community, while retaining control of the project in the short term.

**Comment by kfogel** [comment]
Thanks, @gaffer01.  Looking forward to seeing it.
