### ISSUE TITLE
Apache TinkerPop3 Support

### ISSUE THREAD

**Issue by okram** [GovernmentCommunicationsHeadquarters/Gaffer#11]
Are there plans to support Apache TinkerPop3 and Gremlin? http://tinkerpop.apache.org.

If so, the TinkerPop community would be more than happy to help orient the effort.

**Comment by gaffer01** [comment]
We are interested in a Tinkerpop API, and whether it could support the range of filtering, aggregation and bulk query options we provide. We do not currently have a timescale for investigating this though. If anyone wants to investigate this, that would be great.
