### ISSUE TITLE
Create an operation cache

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#112]
This might involve 2 operations:
- UpdateCache - stores the input in the cache (with a provided string key) and returns the input
- FetchCache - returns the entire cache
- FetchCachedResults - returns results from the cache with the provided key

The cache should work for elements or just objects and allow users to cache steps of an operation chain separately - this could be achieved by passing in a key as part of the UpdateCache operation.

For small amounts of data a ```HashMap<String, Iterable<Object>>``` would work for for the cache. We could consider added options to UpdateCache to specify the type of cache you wish to use - for example the cache could be a new Gaffer graph.
 
For example:

- Build up a graph of all vertices traversed
```java
final Iterable<?> cachedResults = graph.execute(new Builder()
    .first(new GetAdjacentEntitySeeds.Builder()
            .addSeed(new EntitySeed("A"))
            .build())
    .then(new UpdateCache())
    .then(new GetAdjacentEntitySeeds())
    .then(new UpdateCache())
    .then(new FetchCachedResult())
    .build());
```

- Get related edges and entities separately
```java
final Map<String, Iterable<?>> cachedResults = graph.execute(new Builder()
        .first(new GetAdjacentEntitySeeds.Builder()
                .addSeed(new EntitySeed("A"))
                .build())
        .then(new UpdateCache("adj-seeds"))
        .then(new GetEntitiesBySeed())
        .then(new UpdateCache("entities"))
        .then(new FetchCachedResult("adj-seeds"))
        .then(new GetRelatedEdges())
        .then(new UpdateCache("edges"))
        .then(new FetchCache())
        .build());
```

**Comment by p013570** [comment]
gh-127 will extend this cache operation and add the functionality to return a new gaffer graph.

**Comment by a09631** [comment]
Pull request approved and merged in to develop branch.
