### ISSUE TITLE
Create operation to return all elements

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#119]
This could be implemented in Accumulo using a Range with infinite start and end keys.

This should probably be a core operation.

**Comment by p013570** [comment]
The accumulo store inserts all edges both ways round so we need to make sure that when all the elements are returned via the new operation we don't return these extra flipped edges. In order to differentiate the flipped undirected edges we need to add an additional flag to the edge key bytes.

**Comment by a09631** [comment]
Pull request approved and merged in to develop branch.
