### ISSUE TITLE
SimpleQuery.java not runnning in Gaffer 0.3.2

### ISSUE THREAD

**Issue by pranita-s** [GovernmentCommunicationsHeadquarters/Gaffer#121]
After putting necessary jar files in Accumulo's lib directory,the example JAR file in ext folder and running SimpleQuery.java, following error is coming:

ubuntu@ip-172-31-24-17:~/Downloads/installs/accumulo-1.6.4$ bin/accumulo gaffer.example.SimpleQuery
java.lang.NoClassDefFoundError: gaffer/operation/Operation
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at org.apache.accumulo.start.Main.main(Main.java:115)
Caused by: java.lang.ClassNotFoundException: gaffer.operation.Operation
        at org.apache.commons.vfs2.impl.VFSClassLoader.findClass(VFSClassLoader.java:175)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 5 more
gaffer.example.SimpleQuery must implement a public static void main(String args[]) method

The lib directory of Accumulo is as follows:
ubuntu@ip-172-31-24-17:~/Downloads/installs/accumulo-1.6.4/lib$ ls
accumulo-core.jar
accumulo-examples-simple.jar
accumulo-fate.jar
accumulo-gc.jar
accumulo-master.jar
accumulo-minicluster.jar
accumulo-monitor.jar
accumulo-native.tar.gz
accumulo-proxy.jar
accumulo-server-base.jar
accumulo-start.jar
accumulo-store-0.3.2-tests.jar
accumulo-store-iterators-0.3.2.jar
accumulo-test.jar
accumulo-trace.jar
accumulo-tracer.jar
accumulo-tserver.jar
commons-math.jar
commons-vfs2.jar
ext
gaffer-core-0.3.2-tests.jar
gson.jar
guava.jar
javax.servlet-api.jar
jcommander.jar
jetty-continuation.jar
jetty-http.jar
jetty-io.jar
jetty-security.jar
jetty-server.jar
jetty-servlet.jar
jetty-util.jar
jline.jar
libthrift.jar
simple-function-library-0.3.2-tests.jar
simple-serialisation-library-0.3.2-tests.jar
slf4j-api.jar
slf4j-log4j12.jar

I have also observed that the JAR file of example folder in version 0.3.2 which contains SimpleQuery.java is very much different then the JAR file which was created in version 0.3.1.
JAR file of version 0.3.2 is-

ubuntu@ip-172-31-24-17:~/Downloads/installs/Gaffer2/example/target$ jar -tvf example-0.3.2.jar
     0 Wed Mar 30 07:45:42 UTC 2016 META-INF/
   131 Wed Mar 30 07:45:40 UTC 2016 META-INF/MANIFEST.MF
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/function/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/function/transform/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/schema/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/generator/
     0 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/serialiser/
  3269 Wed Mar 30 07:45:28 UTC 2016 addData.json
  1928 Wed Mar 30 07:45:28 UTC 2016 complexQuery.json
  5421 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/SimpleQuery.class
  7512 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/ComplexQuery.class
  1808 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/function/transform/StarRatingTransform.class
  1906 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/Review.class
   609 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/schema/Property.class
   422 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/schema/TransientProperty.class
   481 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/schema/Group.class
  1943 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/Viewing.class
  2948 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/SampleData.class
  2108 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/Film.class
  2087 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/Person.class
  1139 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/data/Certificate.class
  2236 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/generator/FilmGenerator.class
  3166 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/generator/DataGenerator.class
  2400 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/generator/ViewingGenerator.class
  2387 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/generator/ReviewGenerator.class
  2198 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/generator/PersonGenerator.class
  1967 Wed Mar 30 07:45:30 UTC 2016 gaffer/example/serialiser/CertificateVisibilitySerialiser.class
  1259 Wed Mar 30 07:45:28 UTC 2016 store.properties
   900 Wed Mar 30 07:45:28 UTC 2016 storeSchema.json
  3467 Wed Mar 30 07:45:28 UTC 2016 dataSchema.json
   633 Wed Mar 30 07:45:28 UTC 2016 simpleQuery.json
     0 Wed Mar 30 07:45:42 UTC 2016 META-INF/maven/
     0 Wed Mar 30 07:45:42 UTC 2016 META-INF/maven/gaffer/
     0 Wed Mar 30 07:45:42 UTC 2016 META-INF/maven/gaffer/example/
  5186 Wed Mar 30 07:42:10 UTC 2016 META-INF/maven/gaffer/example/pom.xml
    98 Wed Mar 30 07:45:40 UTC 2016 META-INF/maven/gaffer/example/pom.properties

JAR file expansion of version 0.3.1 is included in the issue #77 
Both of them are very different. Is this the possible reason why SimpleQuery.java is not running or am I missing something ?

**Comment by james010101101** [comment]
Hi @pranita-s 

The jar you are trying to run doesn't have its dependencies packed into itself, which is why you are seeing that error.
You need to run the jar's with -jar-with-dependencies in their name for them to run.
In order to create these jar's you need to enable the exampleJar profile when running maven with the -P exampleJar option.

For example mvn install -P exampleJar

I've also added this info to our wiki page : https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/wiki/Getting-Started#examples

**Comment by pranita-s** [comment]
Thanks for the help ! But now another error is occurring:
ubuntu@ip-172-31-24-17:~/Downloads/installs/accumulo-1.6.4$ bin/accumulo gaffer.example.SimpleQuery
Thread "gaffer.example.SimpleQuery" died com/fasterxml/jackson/core/util/ByteArrayBuilder
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/ByteArrayBuilder
        at gaffer.data.elementdefinition.ElementDefinitions.<clinit>(ElementDefinitions.java:50)
        at gaffer.graph.Graph.loadDataSchema(Graph.java:384)
        at gaffer.graph.Graph.createStore(Graph.java:337)
        at gaffer.graph.Graph.<init>(Graph.java:206)
        at gaffer.graph.Graph.<init>(Graph.java:188)
        at gaffer.graph.Graph.<init>(Graph.java:151)
        at gaffer.example.SimpleQuery.run(SimpleQuery.java:82)
        at gaffer.example.SimpleQuery.main(SimpleQuery.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.accumulo.start.Main$1.run(Main.java:141)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.ByteArrayBuilder
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at org.apache.accumulo.start.classloader.AccumuloClassLoader$2.loadClass(AccumuloClassLoader.java:273)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 14 more

**Comment by p013570** [comment]
Hi @pranita-s 

I've been trying to replicate your problem, but I am struggling. When I do:
```bash
mvn install -P exampleJar
```
it produces the example-simple-query-jar-with-dependencies.jar and, for me, it does include com/fasterxml/jackson/core/util/ByteArrayBuilder. As this class is in the jar, when this jar is deployed on Accumulo, Accumulo should be able to find the class.

Please could you check your example-simple-query-jar-with-dependencies.jar so we can try and narrow down the problem. If you run the following it should list the ByteArrayBuilder.class file contained in the jar:
```bash
jar -tvf example/target/example-simple-query-jar-with-dependencies.jar | grep com/fasterxml/jackson/core/util/ByteArrayBuilder
```
On a side note, the examples are set up to run on a mock Accumulo store, purely as a quick walk through of the framework. If you want to run the example on a real Accumulo cluster then you may need to make a few changes. For example, you would need to change the store.properties file (in example/src/main/resources) - change the value of gaffer.store.class to gaffer.accumulostore.AccumuloStore and update the other relevant properties.

**Comment by pranita-s** [comment]
Hi, Thanks for the reply ! I am running examples on mock Accumulo store itself.
 I tried the command and following is the output -

ubuntu@ip-172-31-24-17:~/Downloads/installs/Gaffer$ jar -tvf example/target/example-simple-query-jar-with-dependencies.jar | grep com/fasterxml/jackson/core/util/ByteArrayBuilder
  4864 Mon Sep 14 19:44:58 UTC 2015 com/fasterxml/jackson/core/util/ByteArrayBuilder.class

It appears that it does exist but still,I am getting error.

**Comment by p013570** [comment]
OK, from your previous comments it looked like you were trying to run the jars on a real Accumulo cluster. 

To run the example on the mock Accumulo store it is actually quite straight forward - it doesn't require an Accumulo cluster or even any additional Accumulo jars, everything it needs is packaged inside the jar-with-dependencies. 

To run it all you need is java and to execute the jar:
```sh
java -jar example-simple-query-jar-with-dependencies.jar
```

**Comment by pranita-s** [comment]
Thanks ! 
I tried to built it on Windows but it failed. I am able to run programs on Ubuntu. I read the User guide and wished to run programs in IDE.
Can it be only built in Linux based system ?

**Comment by p013570** [comment]
Assuming your initial question has been answered, please reopen the issue if you need to. We have raised a bug gh-164, to fix the build on Windows.
