### ISSUE TITLE
AddElementsFromHdfs builder should allow chaining of builder methods

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#124]
When using the AddElementsFromHdfs builder if you do .option(...) then a MapReduceOperation.Builder object is returned. This prevents uses from chaining builder methods together such as:
```java
.option(...)
.mapperGenerator(...)
```
The parent builder methods need to be overridden and the builder return type needs to be changed to AddElementsFromHdfs.Builder.

**Comment by james010101101** [comment]
Merged
