### ISSUE TITLE
Improve the integration tests module

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#132]
The tests should be more consistent and test all the different store traits. 

The tests should be able to be run on external stores. Currently the only way to run the tests against a store is to include the store as a dependency in the integration-test module. We should switch this around so the integration tests are run from the accumulo-store module and from the array-list-store module.

**Comment by p013570** [comment]
Now if you want to run the integration tests over your store all you have to do is create a test file named [store-name]ITs.java, which extends AbstractStoreITs and create a default constructor that calls ```super(StoreProperties, ...)```. The constructor should create your store properties and if you have any special store schema configuration then also pass that to the super constructor - see AccumuloStoreITs.java for an example.

**Comment by a09631** [comment]
Pull request merged in to develop branch.
