### ISSUE TITLE
how to speed up queries

### ISSUE THREAD

**Issue by OpenZYK** [GovernmentCommunicationsHeadquarters/Gaffer#143]
Hi gaffer guys,

I want to know how to speed up queries, in our sense, there are 70000000+ verticls and 30000000+ edges, we have 8 accumulo servers,

it takes 4 seconds for 1-level depths, and 6 seconds for 2-level depths, 8 seconds for 3-level depths, is it NORMAL ?

how I speed up the query process and whether it connects the zookeeper every time when I query?

**Comment by james010101101** [comment]
Hi ,
This performance seems slow to us especially the initial query, but we don't have enough information to diagnose the performance
We may be able to better tell you what's causing this if you could answer a few questions,

How many seeds are you using for your initial query?

What operations are you chaining together to do your depths?

How many results are you getting at each depth?

How are you querying Accumulo, through a rest-api or through a java app on the Accumulo cluster etc?

What kind of specifications do the Accumulo servers your running on have, are they virtual machines?

What are you using as your Identifiers? Are they Strings, Integers etc? And what serialiser did you choose as your Identifier Serialiser, in addition what serialisers are in use for your properties? 
The default serialisation for all items if not specified is java serialisation which is very slow which affects performance of querying heavily, its much better to choose serialisers appropriate for your data types from the simple-serialisation-library if you want performance.
