### ISSUE TITLE
Accumulo store - should initialisation create table?

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#166]
In the LoadAndQuery1 example, if a query is made before elements have been added then an error is thrown as the table hasn't been created. It should be possible to query a graph which no data has been put into.

It should also be possible to create a graph, and then insert data from multiple independent processes. In this case it is important that the table exists before the data insertion starts.

Suggest that the initialise method on AccumuloStore creates the table.

**Comment by gchqdev03** [comment]
I think it would be preferable to return a meaningful exception if someone tries to query a table that does not exist rather than creating a new table anytime someone attempts to query a table that doesn't exist

**Comment by gaffer01** [comment]
The point is that initialising a graph with particular store properties should cause that store to be instantiated. Only initialising it when addElements is called leads to problems when multiple parallel processes simultaneously start writing to a new store.

You shouldn't be able to query a table that doesn't exist. You query via a graph and initialising the graph causes the store and hence table to be initialised. If you don't have permissions to create a table then a meaningful exception should be thrown.

**Comment by james010101101** [comment]
Merged into develop.
