### ISSUE TITLE
Equals method on Element

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#167]
The equals method on Element ignores the Properties. There is a deepEquals method to perform an equals if it is desired that the Properties are included in the test.

What should the default be? The Properties are an integral part of the Element (cf Gaffer1 where the Properties were separate) so suggest the default is that the Properties should be included in the equals.

We want to support multigraphs, where there can be multiple edges between nodes (even of the same element type), so it feels more consistent with that aim to have Properties included in the equals.

If the consensus is to leave it as it is, can we record the justification here?

**Comment by p013570** [comment]
I agree, properties are an integral part of elements so let’s make the equals method compare everything in an element.

**Comment by p013570** [comment]
Merged into develop.
