### ISSUE TITLE
Add store validation trait

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#17]
A new store trait (STORE_VALIDATION) will be used to allow store implementations to continuously validate elements and remove elements that are no longer valid. This will also allow custom age off and expiration filters to be written based on FilterFunctions. For example, you could age off elements based on properties, e.g (timestamp > x) AND (count < y).

Accumulo store should support store validation by adding a new validation iterator. 
NOTE - the previous AgeOff accumulo iterator will no longer be used. To migrate to using the new store validator, store schemas will need to be updated to add an AgeOff validator function for each element group that needs to be aged off.  

Added a new AccumuloProperty "gaffer.store.accumulo.enable.validator.iterator" to disable the store validation if it is not required.

The previous VALIDATION trait has been removed as validation is handled via a validation operation automatically so it wouldn't make sense for a store not to be able to validate the elements. There is still the option to disable validation.

**Comment by p013570** [comment]
### Migration Steps
The Accumulo AgeOff filter has been removed and replaced with store validation. The schema validation functions you specify are now used to continually validate and remove invalid elements. This allows for custom expiration of elements as well as standard age off. 

If you were making use of the automatic Accumulo AgeOff filter then next time you create a new table it will no longer be added - instead a validator filter is added. 
Instead ensure each element group that you wish to be aged off has a timestamp property with a type similar to "timestamp", then in the types section add something similar to the following:
```json
"timestamp": {
    "class": "java.lang.String",
    "validator": {
	    "functions": [
	      {
	        "function": {
	          "class": "gaffer.function.simple.filter.AgeOff",
	          "ageOffDays": 365
	        }
	      }
	    ]
  	}
}
```

To migrate to the new validator filter on an existing table do the following:
- Open the accumulo shell and remove the AgeOff iterator.
- Assemble a jar containing the main class AddUpdateTableIterator and any other functions or serialisers you are using in your schemas.
- Then run the AddUpdateTableIterator jar on accumulo with your new schema paths, property path and the 'update' argument.

**Comment by a09631** [comment]
Pull request merged into develop.  Testing to occur before merge to master.
