### ISSUE TITLE
Swagger Servlet does not get loaded automatically in Tomcat

### ISSUE THREAD

**Issue by gchqdev03** [GovernmentCommunicationsHeadquarters/Gaffer#170]
When creating an example REST project containing the Gaffer rest-api module as a dependency and deploying to Tomcat 9, the SwaggerJaxrsConfig servlet does not get loaded on startup and thus Swagger  does not work correctly.

This looks to be due to the way the Servlet is defined in the code:
`@WebServlet(name = "SwaggerJaxrsConfig", loadOnStartup = 2)`
According to the Servet 3.x spec at least one URL pattern MUST be declared in either the value or urlPattern attribute of the annotation

One solution would be the following:
`@WebServlet(name = "SwaggerJaxrsConfig", urlPatterns = {"/SwaggerJaxrsConfig"}, loadOnStartup = 2)`

**Comment by gchqdev03** [comment]
Will be fixed in gh-131

**Comment by gchqdev03** [comment]
Fixed in pull request G131 rest interface

**Comment by p013570** [comment]
Merged into develop as part of gh-131.
