### ISSUE TITLE
Create a User object with userId and dataAuths

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#186]
Currently operation authorisations are provided using an operation option in Accumulo. It should be moved out of Accumulo as other stores will want authorisations too. It would be clearer if a User object was passed to Graph along with the operation/operation chain. This user object should contain the following:

- userId - to allow the graph to log information about the operations carried out
- dataAuths - user authorisations for the type of data they are allowed to see

In the future we will add operationAuths for restricting users from executing certain operations. This will be added in gh-129.

This change will mean the accumulo authorisations option should be removed and the user object should be used instead.

**Comment by p013570** [comment]
## Migration Steps
The Graph and Store classes now have an additional 'User' parameter required for the execute methods.
The User object contains the id of the user executing the operation and any data authorisations the user has. The default constructor for User will create a user with ID = "UNKOWN"

REST API implementations that have user based requests should override the createUser method and return a User object, populated with the user's id and auths.

**Comment by a09631** [comment]
Pull request approved and merged into develop.
