### ISSUE TITLE
Operation chain builder generics stops some valid operation chains

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#198]
It should be possible to chain a getAdjacentEntitySeeds operation with a getRelatedEdges, i.e.:
```java
new OperationChain.Builder()
    .first(new GetAdjacentEntitySeeds.Builder()
            .addSeed(new EntitySeed("1"))
            .build())
    .then(new GetRelatedEdges())
    .build();
```

The operation chain requires the output from op 1 to be compatible with the input to op2. In this example the output from op1 is Iterable[EntitySeed] and the input from op2 is Iterable[ElementSeed]. As EntitySeed is an extension of ElementSeed this should be allowed.

We could open up the operation chain so it doesn't check the generic types - but this could lead to operation chains being invalid. Alternatively we could change the input type of GetRelatedEdges to [? extends ElementSeed]. This second option is preferable, but knock on implications need to be checked and we should should also update other operations such as GetRelatedEntities to [? extends ElementSeed] too.

### Current workaround
Cast the GetRelatedEdges into GetEdges and ignore the unchecked assignment warning.
```java
new OperationChain.Builder()
    .first(new GetAdjacentEntitySeeds.Builder()
            .addSeed(new EntitySeed("1"))
            .build())
    .then((GetEdges) new GetRelatedEdges())
    .build();
```

**Comment by p013570** [comment]
## Migration Steps
GetRelatedEntities, GetRelatedEdges and their builders are now generic so if you use these classes in java you will need to parameterise them with ElementSeed, EdgeSeed or EntitySeed.

The above example would now be:
```java
new OperationChain.Builder()
    .first(new GetAdjacentEntitySeeds.Builder()
            .addSeed(new EntitySeed("1"))
            .build())
    .then(new GetRelatedEdges<EntitySeed>())
    .build();
```

**Comment by a09631** [comment]
Pull request approved and merged in to develop branch
