### ISSUE TITLE
Example jar has invalid main class

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#201]
This was introduced by issue gh-14 when packages were renamed.

We should probably just remove the main class and allow users to chose which example class to run on the command line.

**Comment by p013570** [comment]
## Migration Steps
To run the examples on the command line you now need to specify which example to run by providing the class name as an argument and using 'java -cp' instead of 'java -jar'
```bash
java -cp example-jar-with-dependencies.jar gaffer.example.gettingstarted.analytic.LoadAndQuery1
```

**Comment by a09631** [comment]
Pull request approved and merged in to develop branch.
