### ISSUE TITLE
Error message in view and schema function validation is not clear

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#210]
The schema and view function validation creates an incorrect error message when a function selection type cannot be found in the view/schema. The log statement is in classes SchemaElementDefinitionValidator and ViewValidator.

For example, the error message currently says:
```
Function gaffer.function.simple.filter.IsMoreThan is not compatible with selection types. Function input type java.lang.Comparable is not assignable from selection type with a null class
```
It would be much clearer if it just said one of the following.
if type definition is null:
```
No type definition defined for "property1". Please ensure it is defined in the schema.
```
if type definition has no class type:
```
No class type found for type definition "type1" used by property "property1". Please ensure it is defined in the schema.
```

**Comment by a09631** [comment]
Pull request approved and merged in to develop branch.
