### ISSUE TITLE
Create Operation Chain Example

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#215]
This requires a new java/json example in the getting started module and a walkthrough of the code on the [wiki](https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/wiki/Getting-Started#examples).

**Comment by p013570** [comment]
Needs to be merged in after gh-214.

**Comment by a09631** [comment]
Pull request approved, branch merged in to develop.
