### ISSUE TITLE
AddElementsFromHdfs - check folders first

### ISSUE THREAD

**Issue by gchqdev03** [GovernmentCommunicationsHeadquarters/Gaffer#234]
When running the AddElementsFromHdfs Operation for Bulk Import, if the failure path does not already exist then the operation does not tell you until after the initial Map/Reduce job has run. It would be useful to do all directory checks upfront and present error to the user accordingly before running the actual operation rather than having to wait potentially hours to find that the second part of the operation failed.

Similarly, the output path is not allowed to exist before the job is run, yet the failure path has to exist. Seems a bit inconsistent

**Comment by p013570** [comment]
Merged into develop
