### ISSUE TITLE
ArrayList store should return results lazily

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#238]
The ArrayList store produces a List of results when queried. Stores should return their results lazily, i.e. only extract data from the underlying storage layer as the user consumes it by reading through the iterable of results. This avoids unnecessary work if the user decides to not read through all the results. It also avoids memory pressure in the store - materialising all the edges for a high-degree node into a set could use a lot of memory.

**Comment by p013570** [comment]
The ArrayList store was initially intended to demonstrate different types of Gaffer stores. However, it isn't particularly efficient and lacks a lot of the features you get from using a mock accumulo store. I don't think it is worth spending time refactoring this store and adding the extra features in. Instead we could remove the store and implement a different store see gh-278 or gh-279.
