### ISSUE TITLE
Create an operation execution context

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#250]
For ticket gh-247 and others in the future we need to pass context between execution of operations. Currently we just pass a user object between operations, but it would be more flexible to pass a context object that contains the user and other information such as a cache (this may change in gh-247 to export configuration).

The cache operations should then be handled with operation handlers instead of having the logic directly in the store class.

**Comment by a09631** [comment]
Pull request approved and merged in to develop branch.
