### ISSUE TITLE
Serialisation for Ints and Longs

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#253]
Currently there are 2 serialisations for Ints and for Longs. One is slow because it converts the int to a String and converts that to a byte array but has the advantage of only needing 1 byte to serialise some small values; the other is likely quicker but always uses 4 bytes. In many cases, when ints are stored they are mostly very small. The approach of Hadoop's VIntWritable should be (almost) as quick as the latter and as compact as the former. So suggest adding an implementation based on this. To avoid introducing a dependency on Hadoop in the serialisation library, suggest just copying the code from Hadoop, and acknowledging it in the NOTICES file.

**Comment by p013570** [comment]
This was included in release 0.4.0.
