### ISSUE TITLE
Create ComparableMin aggregator

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#255]
Common aggregation methods for Dates are to take the earliest or the latest. Gaffer should provide aggregators that can be used for this. ComparableMax can be used to take the latest Date. There is no ComparableMin - one should be implemented.

**Comment by gaffer01** [comment]
ComparableMax can be used to take the latest Date. There is no ComparableMin - one should be implemented.

**Comment by james010101101** [comment]
Merged into develop
