### ISSUE TITLE
Summarising over RowID's in accumulo

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#258]
We should add the ability to summarise over rowID's in a range query that will aggregate those values over the range provided grouped by Column Family 

I.e in a Graph of Edge's 
A-B GROUP 1 Count 6 
A-B GROUP 2 Count 4 
A-C GROUP 1 Count 1

With the summarise option on, a range query of A-C would return 2 edges.
One (A-B+A-C) with a count of 7 
And one A-B with a count of 4.

**Comment by gaffer01** [comment]
Can you clarify what this behaviour means? What is the first edge returned, i.e. what does (A-B+A-C) mean, what is the source and what is the destination?

This behaviour is not generally what is wanted from a range scan. Generally from a range scan you would just want those 3 edges returned. Is it possible to turn the behaviour described above off (and still do aggregation of the values over column family and visibility)?

If the data was:

A-1 GROUP1 Count 1
A-2 GROUP2 Count 2
A-3 GROUP1 Count 1
A-4 GROUP2 Count 2
...
A-1000000 GROUP1 Count 1
A-1000001 GROUP2 Count 2

then the the aggregated edge would contain a lot of data (i.e. whatever A-B+A-C means would be large), and if there were a lot of groups then a lot of data would need to be cached before it could be output.

In general this breaks the idea that the iterators read data, aggregating into one element, then when the next group is reached, the element is output - it's a very low state process.

Does this behaviour work across tablets? A-C might be in a different tablet (and on a different tablet server) to A-B. Does the aggregation work in this case?

**Comment by james010101101** [comment]
"What is the first edge returned, i.e. what does (A-B+A-C) mean, what is the source and what is the destination?"
Currently -> A-B+A-C will be the summarisation of the properties and the source and Destination will be those of the last key returned by the iterator.

"Is it possible to turn the behaviour described above off (and still do aggregation of the values over column family and visibility)?"
Not currently, you can't aggregate over column families anyway but I assume you meant qualifier

**Comment by gaffer01** [comment]
The most common use case for range scans is to return all edges for vertices in a certain range, doing standard aggregation of properties over column qualifier (e.g. different time windows), e.g. if the graph is:

A->B GROUP1 date=20160101 count=10
A->B GROUP1 date=20160102 count=20
A->C GROUP1 date=20160101 count=5
B->E GROUP1 date=20160101 count=2
B->E GROUP1 date=20160102 count=3
C->F GROUP1 date=20160101 count=2
C->F GROUP1 date=20160102 count=4
D->G GROUP1 date=20160101 count=1

and we specify a range of B to C, the desired edges are:

B->E GROUP1 date=20160101-02 count=5
C->F GROUP1 date=20160101-02 count=6

From what you say, this is not currently supported and is not the standard meaning of doing aggregation in a range scan?

"Currently all aggregation assumes that all data for the provided ranges lives on the same tablet server, client side aggregation is needed for all cases of aggregation to catch cases where the desired ranges are split across tablet servers."
Is the client side aggregation implemented? If not then the current implementation will not always work and needs fixing.

**Comment by james010101101** [comment]
"Is the client side aggregation implemented? If not then the current implementation will not always work and needs fixing."

**Comment by james010101101** [comment]
I've Implemented a new Operation that takes one column family and uses this to Summarise over Range's of RowID's within that column family to create one summarised result for that range.

I ran into some questions when implementing Client Side Aggregation so this will be added later on a separate branch to the operation so at current results may be only partially aggregated particularly in large graphs.

Both methods of aggregation discussed above are possible, ROWID aggregation being a specific accumulo operation.

**Comment by p013570** [comment]
Merged into develop
