### ISSUE TITLE
Specification of aggregation logic

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#260]
Gaffer has the concept of aggregation. There are two types: persistent and query time. Technically though, Gaffer does not perform aggregation, it performs a reduce function: a group-by followed by an aggregation.

Currently, in the Accumulo store, aggregation is specified by specifying aggregators for some / all of the properties. The group-by function is not specified explicitly. It is specified implicitly by the choices the user makes about where properties go in Accumulo's key and value.

There are a few problems with this approach:

- It is too easy to get wrong.
- The concepts of an Accumulo key and a group-by key for the aggregation are confused.
- If a store that has no concept of a key is used, or if Accumulo is used in a different way, then there is no mechanism to specify the group-by function.
- The writer of the schema has to have knowledge of internal Accumulo concepts like column qualifier, visibility and value.

It would be better to specify, on a per-group basis, the desired group-by logic. For example, suppose an edge of group G has the following properties: time window, visibility, count. The user wants persistent aggregation to happen over time window and visibility, e.g. suppose the following edges are inserted:

- A->B of group G with timewindow=20160101-02, visibility=public, count=1
- A->B of group G with timewindow=20160101-02, visibility=private, count=1
- A->B of group G with timewindow=20160101-02, visibility=public, count=2

The the user wants the public visibility edges to be merged so that the database should contain:

- A->B of group G with timewindow=20160101-02, visibility=private, count=1
- A->B of group G with timewindow=20160101-02, visibility=public, count=3

To specify this behaviour, the following properties are needed:

- property=count:
  - type=int
  - aggregator=sum
  - aggregationkeys=timewindow,visibility

The Accumulo store should be able to decide where to store the three properties based on this specification (in practice it might be necessary for the same aggregation keys to be specified for all the properties within a group, but this can be checked at store creation time).

Now consider query-time aggregation and suppose the graph contains:

- A->B of group G with timewindow=20160101-02, visibility=private, count=1
- A->B of group G with timewindow=20160101-02, visibility=public, count=2
- A->B of group G with timewindow=20160102-03, visibility=private, count=5
- A->B of group G with timewindow=20160103-04, visibility=public, count=8
- A->C of group G with timewindow=20160107-08, visibility=private, count=100

There are multiple types of query-time aggregation that the user might want to be performed when A is queried for, e.g.

- (1) Aggregate timewindow, visibility and count to get:
  - A->B of group G with timewindow=201601-04, visibility=private&public, count=16
  - A->C of group G with timewindow=20160107-08, visibility=private, count=100
- (2) Aggregate visibility and count to get:
  - A->B of group G with timewindow=20160101-02, visibility=private&public, count=3
  - A->B of group G with timewindow=20160102-03, visibility=private, count=5
  - A->B of group G with timewindow=20160103-04, visibility=public, count=8
  - A->C of group G with timewindow=20160107-08, visibility=private, count=100
- (3) Aggregate destination, timewindow, visibility and count to get:
  - A->{B,C} of group G with timewindow=20160101-08, visibility=private&public, count=116

What is needed to specify these different behaviours?

- Case (1): Aggregate functions for timewindow, visibility and count. Aggregation keys of edge and group.
- Case (2): Aggregate functions for visibility and count. Aggregation keys of edge, group and timewindow.
- Case (3): Aggregate functions for vertex, timewindow, visibility and count. Aggregation key of group.

In practice, the types of aggregation that can be performed are limited by the capabilities of the store. In the case of Accumulo, one wants to limit the amount of data cached in the tablet server as the aggregation is performed. For example, it is unlikely to be sensible to aggregate over destination, timewindow, visibility but not count - that would require caching an edge for each distinct count, and nothing can be output until all of A's edges have been read. This could mean caching millions of edges and would put strain on the tablet server.

Currently the view is not flexible enough to allow these different types of group-by logic to be specified, and the store cannot specify which types it supports and which it doesn't. This has already led to confusion about the natural meaning of "aggregation" in range scans.

Again, the meaning of aggregation is not clearly defined enough.

Ordering of properties:

In an Accumulo store, the natural way to implement persistent aggregation is to put the grouping keys in the column qualifier and the values to be aggregated in the value. The ordering of the properties in the column qualifier effects the efficiency of some queries. For example, suppose that timewindow and visibility are in the column qualifier and the user queries for the edge A->B with a filter saying that only timewindow 20160102-03 is required. If the timewindow is the first property in the column qualifier then the range scan set up to find everything about edges A->B can skip all other timewindows. If the filter says that all timewindows are required but only one visibility is required then this has to be done by a filtering iterator. Currently the Accumulo store is not smart enough to spot this opportunity and optimise this query. This is really a different issue to the above aggregation issues but it is mentioned here because it has been said that allowing the user to specify in the schema where properties go in Accumulo's key-values allows these sort of optimisations later. This may be true, but again there is no need to specify rowkeys, column qualifier, etc - it is the ordering of the properties in the key that matters.

There is a similar issue with ordering of properties in the value - if the user specifies that in the properties in the graph elements that they receive back from a query they only want to see the count property and not the other properties that are being aggregated, then if the count property is first in the value that can be deserialised and the rest of the value skipped (if there are multiple properties including complex ones such as bitmaps then avoiding the deserialisation cost of these could be significant). Again, this means that the ordering of properties could be important. The store could advertise that ordering properties in certain ways allows it to perform certain optimisations. But again there should be no need to specify which part of the Accumulo key and value.

**Comment by m316257** [comment]
This issue could be resolved like this:

- In the store schema we specify properties that can be used as 'group-by' keys for a reduce operation (group-by followed by aggregation)
- in some stores these group by keys are ordered (for example Accumulo), in others they are not (like a hadoop store where reduce operations are part of map-reduce and, in-principle, any property could be part of a key or a value)
- so in the store schema we no longer have mappings to 'positions', this is implicit in the ordering of the keys.

Additionally

- Security is promoted to being a top-level concept. Gaffer can do this as a filter operation. The idea being that in the store schema, a property can be marked as 'visibility' (or something similar).
- Some stores (such as accumulo) implement their own security. In this case, the actual implementation can be optimised by pushing it down to the store.
- by doing this we allow the grouping of reduce keys described above because if we specify visibilities per element we know that in accumulo these go in the visibility column. Any remaining group-by keys go in the column qualifier.

This should make the concept of reduce on a Gaffer graph a lot more general.

**Comment by p013570** [comment]
# Migration steps
The concept of 'position' has been removed from the schema. Instead there is a now a 'groupBy' field, which should contain the list of property names that should be used as aggregation keys.
There is are also 2 new fields, visibilityProperty and timestampProperty, that defines which properties are for visibility and timestamp.

### Migration for accumulo positions
The following changes may need to be made to your schema files:
- Remove any reference to positions
- Any properties that were previously stored in the column qualifier need to be added to the groupBy properties list - in the order that they are currently stored.
- If you used the visibility position for a property, then this property name should be assigned to the visibilityProperty field.
- If you used the timestamp position for a property, then this property name should be assigned to the timestampProperty field.

### Example schema migration
If your schema was previously:
```json
{
    "entities": {
        "BasicEdge": {
            "vertex": "vertex",
            "properties": {
                "prop1a": "keyed-string",
                "prop1b": "keyed-string",
                "prop2": "simple-string",
                "visibility": "visibility.string",
                "timestamp": "timestamp.long",
            }
        }
    },

    "types": {
        "vertex": {
            "class": "java.lang.String"
        },
        "keyed-string": {
            "class": "java.lang.String",
            "position": "COLUMN_QUALIFIER"
        },
        "string": {
            "class": "java.lang.String",
            "position": "VALUE"
        },
        "visibility.string": {
            "class": "java.lang.String",
            "position": "VISIBILITY"
        },
        "timestamp.long": {
            "class": "java.lang.Long",
            "position": "TIMESTAMP"
        }
    },

     "vertexSerialiserClass": "gaffer.serialisation.simple.StringSerialiser"
}
```

This would need to be migrated to:
```json
{
    "entities": {
        "BasicEdge": {
            "vertex": "string",
            "properties": {
                "prop1a": "string",
                "prop1b": "string",
                "prop2": "string",
                "visibility": "string",
                "timestamp": "long"
            },
            "groupBy": [
                "prop1a", "prop1b"
            ]
        }
    },

    "types": {
        "vertex": {
            "class": "java.lang.String"
        },
        "string": {
            "class": "java.lang.String"
        },
        "long": {
            "class": "java.lang.Long",
        }
    },
    
    "vertexSerialiserClass": "gaffer.serialisation.simple.StringSerialiser",
    "visibilityProperty": "visibility",
    "timestampProperty": "timestamp"
}
```

**Comment by p013570** [comment]
Merged into develop.
