### ISSUE TITLE
Dependencies not resolved by maven?

### ISSUE THREAD

**Issue by unclassified01** [GovernmentCommunicationsHeadquarters/Gaffer#264]
After compiling Gaffer, we needed to manually add the following files to the java project:
accumulo-core-1.7.1.jar
commons-collections-3.2.2.jar
commons-configuration-1.10.jar
commons-io-2.5.jar
commons-lang-2.6.jar
commons-logging-1.2.jar
guava-19.0.jar
hadoop-auth-2.2.0.jar
hadoop-common-2.2.0.jar
jackson-annotations-2.1.2.jar
jackson-core-2.7.4.jar
jackson-databind-2.2.3.jar
libthrift-0.9.1.jar
slf4j-nop-1.7.21.jar
If it's normal (and not due to our problem!) it could be a good idea to write it somewhere in the wiki (better with links to the various projects).

**Comment by p013570** [comment]
Hi @unclassified01,

Thanks for raising the issue. There are a few different jars produced from the build for different usages. 

- If you are simply running the example then there is a maven profile ‘exampleJar’, which produces an example jar with all dependencies.

- If you are deploying the jars onto Accumulo for use by the iterators then you need to use the following jars produced by the default maven build: 
 - accumulo-store-iterators-[version].jar
 - simple-serialisation-[version]-library-serialisers.jar
 - simple-function-[version]-library-serialisers.jar

We will get the wiki updated with this extra information. Hope that helps, if not then let us know which jar has the missing dependencies and we will look into it.

**Comment by p013570** [comment]
Closing as we have updated the wiki with the additional information. Please let us know if you have any other questions.
