### ISSUE TITLE
Default serialisers

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#268]
If the user does not provide a serialiser for a property, then Java serialisation is used if possible. New users of the framework frequently do not specify serialisers and so unknowingly use Java serialisation, which was never intended to be used (and even in test cases such as the MockAccumuloStore can cause problems, for example range scans not working correctly).

Gaffer should automatically use good serialisers for common properties, e.g. short, int, long, float, double, String, Date, HyperLogLogPlus. The expert user can override these if required.

**Comment by p013570** [comment]
## Migration Steps
The following serialisers have been moved into the core serialisation module. This meant the package names needed to be changed. The original classes have been left for compatibility reasons, they are marked as deprecated and will be deleted in a future release. If you are using any of the following serialisers, you will need to switch to use the new ones - update the package names in your schema.

- BooleanSerialiser
- DateSerialiser
- DoubleSerialiser
- StringSerialiser
- TreeSetStringSerialiser
- CompactRawIntegerSerialiser
- CompactRawLongSerialiser

**Comment by p013570** [comment]
Merged into develop
