### ISSUE TITLE
Facing problem in building Gaffer

### ISSUE THREAD

**Issue by pranita-s** [GovernmentCommunicationsHeadquarters/Gaffer#27]
The way explanation is given for its building and deployment is pretty short.
It will be great if  you could help for the same.

I wish to build Gaffer on ubuntu 14.04, as its said to run "mvn clean package" in the top level directory that is : Gaffer

But when i run it , its not successful, and it is throwing errors. I feel that i am missing something.
It will be awesome, if you could guide me for building it the right way !
Thanks in advance !

**Comment by p013570** [comment]
Hi @pranita-s, sorry to hear you're having problems building Gaffer. 

Please could you post the following, so that we can investigate the issues in building the project:
- the output from running "mvn -version"
- the errors you get from running "mvn clean package"

We are currently working on a User Guide, which will go into a lot more detail on how to build and use Gaffer. Hopefully a first draft of the User Guide will be finished by the end of the month.

**Comment by pranita-s** [comment]
Thanks for the prompt reply !

ubuntu@ip-172-31-24-17:~$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_95, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-74-generic", arch: "amd64", family: "unix"

________________________________________________________________________________________________________________________________________________
ubuntu@ip-172-31-24-17:~/Downloads/installs/Gaffer$ mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] gaffer2
[INFO] gaffer-core
[INFO] function
[INFO] serialisation
[INFO] common-util
[INFO] data
[INFO] operation
[INFO] store
[INFO] graph
[INFO] simple-operation-library
[INFO] accumulo-store
[INFO] simple-function-library
[INFO] array-list-store
[INFO] simple-serialisation-library
[INFO] rest-api
[INFO] example
[INFO] gaffer-integration-tests
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building gaffer2 0.3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gaffer2 ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:test-jar (default) @ gaffer2 ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] gaffer2 ........................................... FAILURE [0.769s]
[INFO] gaffer-core ....................................... SKIPPED
[INFO] function .......................................... SKIPPED
[INFO] serialisation ..................................... SKIPPED
[INFO] common-util ....................................... SKIPPED
[INFO] data .............................................. SKIPPED
[INFO] operation ......................................... SKIPPED
[INFO] store ............................................. SKIPPED
[INFO] graph ............................................. SKIPPED
[INFO] simple-operation-library .......................... SKIPPED
[INFO] accumulo-store .................................... SKIPPED
[INFO] simple-function-library ........................... SKIPPED
[INFO] array-list-store .................................. SKIPPED
[INFO] simple-serialisation-library ...................... SKIPPED
[INFO] rest-api .......................................... SKIPPED
[INFO] example ........................................... SKIPPED
[INFO] gaffer-integration-tests .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.172s
[INFO] Finished at: Fri Feb 05 09:28:40 UTC 2016
[INFO] Final Memory: 7M/111M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.4:test-jar (default) on project gaffer2: Error assembling JAR: Failed to create directory: /home/ubuntu/Downloads/installs/Gaffer/target/maven-archiver -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by p013570** [comment]
It looks like a permission issue with the directory /home/ubuntu/Downloads/installs/Gaffer. You will need to give yourself write permissions to the Gaffer folder before you can run "mvn clean package".

You could try:
sudo chown -R ubuntu /home/ubuntu/Downloads/installs/Gaffer
sudo chmod -R u+w /home/ubuntu/Downloads/installs/Gaffer

**Comment by pranita-s** [comment]
It worked like a charm !!!! Thanks a lot !!!
