### ISSUE TITLE
Refactor AddElementsFromHdfsHandler in AccumuloStore

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#29]
The AddElementsFromHdfsHandler should be changed to do the following:

The default behaviour should be set to being; using the options passed to the job through the operation/ including the reducer number and partitioner.

If an option is provided to the operation specifying that the user would like to use standard gaffer behaviour and the user also provides a splits file, then this file will be used as the job's reducer number (Any user provided reducer numbers will be over-ridden by the number of splits +1)  and the AccumuloKeyRange partitioner will be used (Replacing any previously specified one).

If no splits file has been set and the user would like to use standard gaffer behaviour, then gaffer will query the accumulo table for its split points and use those for the number of reducers (+1) and will use the AccumuloKeyRange partitioner. 

General changes will include:
Making clear the purpose of the splits file property in the accumulo store over one provided in an operation with additional comments in the store properties.
Change the default number of reducers for a job up from 1 to 25 to better reflect use at scale.
Adding an option to provide a partitioner to the AddElementsFromHdfs operation builder.

**Comment by p013570** [comment]
merged into develop
