### ISSUE TITLE
Serialisation of properties in Value in Accumulo store

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#293]
In the Accumulo store, properties that go in the Value are serialised by adding the properties to a MapWritable and then converting that to bytes. This serialises the number of properties, then the first property name, and the first property value, then the second property and second value, etc. Storing the property names is wasteful of storage, and as they are specified in the schema is unnecessary. It would take less storage to write out the properties in a defined order (either the order they are specified in the schema, or in alphabetical order), with a list of their serialised sizes in bytes. The advantage of the current approach is that it potentially makes it easier to allow schemas to evolve on an existing table. So this should be optional for the Accumulo store.

**Comment by gaffer01** [comment]
Merged into develop.

**Comment by james010101101** [comment]
## Migration Steps

**This is a breaking change.**

Problems with the previous method of serialisation in the provided KeyPackages means we have ceased support for the old method of serialisation into the Value/Column Qualifier of Accumulo going forward, if you have existing data it is advised to re-import this data into a new gaffer table using the new format, or write a map reduce job to convert the data from the old format to the new.

It is possible to re-implement the old key-packages if you want to migrate versions without migrating your data however this is not advised as this new method is more space efficient and performant, it is highly advised to migrate to the new key-packages as soon as possible.
