### ISSUE TITLE
Locality groups in Accumulo store

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#294]
Accumulo's locality groups could be used so that queries that only require certain groups do not have to scan other groups (see http://accumulo.apache.org/1.7/accumulo_user_manual#_locality_groups). This is very natural with the current approach of storing the group in the column family, as a locality group is just a set of column families.

A sensible default option might be for different groups to be stored in different locality groups. This should speed up scans which require only a subset of the groups. Once locality groups are enabled, Accumulo will automatically take advantage of them when the `fetchColumnFamilies` method is called (which is already used in Gaffer).

**Comment by p013570** [comment]
Merged into develop.
