### ISSUE TITLE
Remove ability to set number of reducers and partitioner for the SampleDataForSplitPoints operation

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#310]
Currently the Operation and Operation Builder for the SampleDataForSplitPoints operation allows you to set a reducer number and a partitioner to be used, these options are inherited from the MapReduce Operation superclass, but for this specific operation these make no sense, 
Therefore when trying to set these methods an error should be thrown indicating that you cannot use these options.

**Comment by p013570** [comment]
Merged into develop
