### ISSUE TITLE
Serialiser for FreqMap

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#313]
It should be possible to serialise FreqMap without using Java serialisation.

**Comment by p013570** [comment]
Merged into develop

**Comment by p013570** [comment]
# Migration steps
FreqMap class has moved into a simple types library, therefore the package name has changed. The full class name has changed fromgaffer.function.simple.types.FreqMap to gaffer.types.simple. FreqMap
