### ISSUE TITLE
"Directed" properties on edges not being serialised

### ISSUE THREAD

**Issue by flitte** [GovernmentCommunicationsHeadquarters/Gaffer#314]
I'm seeing an issue where Gaffer does not appear to be serialising the "directed" properties on edges.

Here's an example of data entered into the graph:

`{
      "class": "gaffer.data.element.Edge",
      "properties": {
        "first_seen": {
          "java.lang.Long": 100000
        },
        "count": 1
      },
      "group": "myEdge",
      "source": "srcId",
      "destination": "destId",
      "directed": false
}`

When the same edge is retrieved by running an operation (GetAllElements), the output is:

`{"class":"gaffer.data.element.Edge","properties":{"first_seen":{"java.lang.Long":100000},"count":1},"group":"myEdge","source":"srcId","destination":"destId"}`

My schema looks like:

`{
  "edges": {
    "myEdge": {
      "source": "string",
      "destination": "string",
      "directed": "true",
      "properties": {
        "first_seen": "timestamp_min,
        "count": "count.int"
      }
    }
  },
  "entities":{
    "myEntity":{
    "vertex": "string"}
  }
}`

Seen on version 0.3.8.

**Comment by flitte** [comment]
This can be resolved by making the following change to the `AbstractJacksonJsonProvider` class in the rest-api module:

```java
protected ObjectMapper createMapper() {
    final ObjectMapper mapper = new ObjectMapper();
    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
  //mapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);
    mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
    return mapper;
}
```

This currently breaks the python shell if the target graph contains undirected edges since the `to_elements` method in the `ResultConverter` (line 53 of gaffer.py) attempts to read the 'directed' property of the edge (which is never serialised if false).

**Comment by p013570** [comment]
We have also come across a few issues with the NON_DEFAULT flag. Initially we thought it would be useful as it would reduce the amount of data sent via the REST API, but it has led to complications.

I agree we should just remove the NON_DEFAULT option.

On a side note, looking at your schema, your 'myEdge' group states the edge should be directed but you are adding undirected edges into your graph. Either you have skipped validation or you may want to ensure you have the following in your dataTypes.json file:

```json
"true": {
  "class": "java.lang.Boolean",
  "validateFunctions": [
    {
      "function": {
        "class": "gaffer.function.simple.filter.IsTrue"
      }
    }
  ]
}
```

**Comment by flitte** [comment]
The amount of data transferred could be reduced by turning off pretty printing (and leaving the formatting to the calling application) or forcing GZip compression - I'm not sure either of these are enforced at the moment?

**Comment by james010101101** [comment]
Pretty print isn't enabled on the JSON serialisation of the results coming back from the rest service, but it is on the provided JSONSerialiser class that is often used on the client end.

**Comment by p013570** [comment]
Merged into develop.
