### ISSUE TITLE
Move Gaffer-Accumulo Store to run on Accumulo 1.7.2

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#324]
Given the Performance enhancements and New Features avavliable to Accumulo since the 1.7 release, 
Including as seen with issue gh-319

It would be a good idea to base Gaffer's Accumulo implementation on the 1.7 branch, preferably the latest at time of writing 1.7.2
This will include updating of other dependencies on which Accumulo relies appropriate versions.

**Comment by p013570** [comment]
Merged into develop.

**Comment by james010101101** [comment]
## Migration Steps

The Versions of Accumulo and Hadoop have been changed to 1.7.2 and 2.6.3 respectively, while the codebase should still be compatible with the previous versions used we will no longer actively support them and the codebase may become incompatible with these versions at any point in the future.
It is advisable if possible to migrate any system running gaffer to the above versions going forward
