### ISSUE TITLE
Create TypeValue vertex type

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#344]
It is common to identify a vertex using a pair of strings, type and value, e.g. customer A or film B. Serialisation of this pair of strings is not trivial, unless it is known for certain that a certain character, e.g. "|", will not appear in either the type or the value (in this case that character can be used as a delimiter). If this is not known, then the serialisation needs to delimit the two strings so that they can be unambiguously deserialised later. This needs to be done in a way that preserves the ordering so that range scans work. One way to do this is to convert each string to a byte array, remove the 0 byte from each of these using `ByteArrayEscapeUtils`, and then use the 0 byte as the delimiter. This should preserver the ordering.

Gaffer should provide a TypeValue type and a serialiser.

Additionally, a TypeSubtypeValue vertex could be provided.

**Comment by james010101101** [comment]
An example of a type value object was created for the testing of gh-335
gaffer-core/operation/src/test/java/gaffer/operation/data/CustomVertex.java
This should be replaced with the Type/Value object created for this issue.

Also on the Serialisation of the object, if the serialiser simply did string10string2.
If the resulting byte array was placed in the vertex in the Accumulo store the currently implemented key packages will call ByteArrayEscapeUtils on the returned byte array to escape the 0 byte. Similarly any other implemented key packages should escape whatever characters are used to delimit the vertex components (if something other than 0 is used)

**Comment by p013570** [comment]
Merged into develop.
