### ISSUE TITLE
Number of reducers for bulk import

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#361]
When bulk importing to Accumulo, the number of reducers is set based on the number of split points. This can cause problems in two situations:

- If there are a large number of split points, but a small amount of data is being ingested, then a large number of reducers are used and this can slow the job down. The method `connector.tableOperations.getSplits(<table name>,<max splits>)` provides optimal splits up to a maximum number.
- If there is a large amount of data to be imported, but the table is new and only has a small number of split points then there will be a small number of reducers and the job will take a long time to run.

Two options to the `AddElementsFromHdfs` operation should be added: the first allows a maximum number of reducers to be specified. The second causes more reducers than the number of splits to be used - there is a method on  `RangePartitioner` called `setNumSubBins` to help with this.

**Comment by p013570** [comment]
Merged into develop.
