### ISSUE TITLE
SplitTableTool ignores first split in file and only reads half the splits

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#377]
The following reads the first line then reads the next and adds it to the set:

```
String line = br.readLine();
while (line != null) {
     splits.add(new Text(br.readLine()));
     line = br.readLine();
}
```

**Comment by gaffer01** [comment]
It also explains why the number of reducers has often been half the number of tablet servers - every second line is ignored (as `readLine` is called twice in the loop).

**Comment by gaffer01** [comment]
This should probably be unit-tested, however suggest creating an issue to add unit tests for the whole end-to-end bulk import process and test this as part of that.

**Comment by james010101101** [comment]
Merged Into Develop
