### ISSUE TITLE
GetOperation shouldn't return an iterable

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#396]
The `GetOperation<SEED_TYPE, RETURN_TYPE>` interface extends `Operation<Iterable<SEED_TYPE>, Iterable<RETURN_TYPE>>`. A get operation might not return an iterable of results. In the case of getting a Spark RDD of results, it returns a single RDD, not an iterable. A get operation could also return its results as a single `Graph` object.

The `GetOperation` interface should be changed so that it extends `Operation<Iterable<SEED_TYPE>, RETURN_TYPE>`.

**Comment by james010101101** [comment]
Merged Into Develop
