### ISSUE TITLE
stop spying on us.

### ISSUE THREAD

**Issue by floodedcodeboy** [GovernmentCommunicationsHeadquarters/Gaffer#4]
what the title says.

**Comment by kvnlng** [comment]
Meh. I say thanks for the code.

**Comment by floodedcodeboy** [comment]
hey, the code is nice... its just I have principles.

**Comment by pculka** [comment]
:D +1

**Comment by sata** [comment]
:thumbsup:

**Comment by bitdivine** [comment]
This is not a place for political disputes.  Please evaporate this issue with one hydrogen bomb. ;-)

**Comment by floodedcodeboy** [comment]
@bitdivine you've been outvoted. as per a democracy...

**Comment by installgen2** [comment]
:+1: 

@bitdivine :eggplant:

**Comment by installgen2** [comment]
@gaffer01 racist!
