### ISSUE TITLE
Add extra logging to the Filter processor

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#42]
If an element fails validation it can be very difficult to find out why. It would be very useful to add additional logging to the Filter processor, so that when an element is filtered out based on a data schema it logs the function name and the property that was invalid. 

We have 2 options:

- When elements are invalid based on a data schema we could log at 'warn' level. When elements are filtered out based on a View it is probably best not to log anything to avoid slowing the operations down - this may require an extra flag to toggle logging on and off in the processor.

- Log at 'debug' level for all filtering (data schema and view). Then users will have to set the level to 'debug' temporarily to see the extra information.

**Comment by james010101101** [comment]
Merged into develop
