### ISSUE TITLE
AbstractCoreKeyAccumuloElementConverter has unnecessary call to System.currentTimeMillis()

### ISSUE THREAD

**Issue by gaffer01** [GovernmentCommunicationsHeadquarters/Gaffer#420]
There are two places in `AbstractCoreKeyAccumuloElementConverter` where there is a call to `System.currentTimeMillis()` which is ignored if a timestamp has been provided. As this is called for every `Element` that is inserted, that's a lot of potentially expensive overhead. The `buildTimestamp` method should call `System.currentTimeMillis()` only if it needs to because no timestamp has been provided.

Two other issues with this class could be fixed at the same time (separate issues can be raised if necessary): there is a reference to `new byte[0]` but elsewhere in the class `AccumuloStoreConstants.EMPTY_BYTES` is used instead; in `getKeyFromEntity` there is a comment that "Row key is formed from identifier and group" - this is not true - it should say "Row key is formed from vertex".

**Comment by p013570** [comment]
Merged into develop.
