### ISSUE TITLE
Improve Function library interfaces

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#44]
Currently it is awkward to write Function implementations due to the inputs and outputs being an Object[]. It would also be nice if we could remove the requirement for the Inputs and Outputs annotation to define the object types.

Ideally a FilterFunction should not have to cast the parameters into the required types, something like:
```java
public class FilterFunctionExample extends FilterFunction {
    @Override
    public boolean filter(final String param1, final Integer param2) {
        // do something
    }
}
```

The Function package names could also be improved to make it a bit clearer what interfaces you should use.

The method name in FilterFunction could be "isValid" instead of "filter" this would make it clearer what the method does.

We have investigated several different options, each having different advantages, but none are perfect. The best so far is something like:

```java
public abstract class FilterFunction {
    public abstract boolean isValid(Object[] input);

    public abstract class FilterFunction1<PARAM_1> extends FilterFunction {
        public boolean isValid(Object[] input) {
            return isValid((PARAM_1) input[0]);
        }

        protected abstract boolean isValid(PARAM_1 item);
    }
}

public class IsTrue extends FilterFunction1<Boolean> {
    public boolean isValid(Boolean item) {
        return Boolean.TRUE.equals(item);
    }
}
```

In order to deal with the Object[] return types in AggregateFunctions and TransformFunctions we could return an NTuple, where NTuple implementations wrap an Object[] and have generic types like:
```java
TwoTuple<ITEM_1, ITEM_2>
ThreeTuple<ITEM_1, ITEM_2, ITEM_3>
```

**Comment by p013570** [comment]
Needs further investigation.

**Comment by a09631** [comment]
Pull request accepted, merged branch into develop.

**Comment by p013570** [comment]
### Migration Steps

Ensure any simple custom functions that take a single input/output extends one of the following:
SimpleFilterFunction, SimpleAggregateFunction or SimpleTransformFunction and add in the generic type for your function.
