### ISSUE TITLE
Add validation to Views

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#46]
Before using a View in an operation it would be useful to validate similar to how we validate data schemas to avoid class cast exceptions.

**Comment by p013570** [comment]
## Migration Steps
Views no longer require properties or identifiers to be provided. Instead they just require transient properties (along with filterFunctions and transformFunctions).

Views will now be validated before an operation is executed to ensure it is valid against the graph schema.

So a valid view now looks like this:

```json
"view": {
  "entities": {
    "summaryGroup": {
      "transientProperties": {
        "average": "java.lang.Float"
      },
      "filterFunctions": [
        {
          "function": {
            "class": "gaffer.function.simple.filter.IsMoreThan",
            "value": 5
          },
          "selection": [
            {
              "key": "count"
            }
          ]
        }
      ],
      "transformFunctions": [
        {
          "function": {
            "class": "gaffer.example.function.transform.Average"
          },
          "selection": [
            {
              "key": "count"
            },
            {
              "key": "sum"
            }
          ],
          "projection": [
            {
              "key": "average"
            }
          ]
        }
      ]
    }
  }
}
```

this would only be valid as long as the corresponding schema defines properties "count" and "sum"

**Comment by a09631** [comment]
Merged into develop.
