### ISSUE TITLE
seeds method on AbstractGetOperationBuilder throws IllegalStateException when not null.

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#52]
See AbstractGetOperationBuilder line 189, should be if null == seeds.

**Comment by p013570** [comment]
I can't seem to reproduce this. Please could you provide the code you were using that throw the exception.

**Comment by james010101101** [comment]
This issue seems has already been fixed on develop branch.
Closing issue.
