### ISSUE TITLE
Rest Api - Investigate limiting results of an operation chain

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#57]
Should an N limit apply to only the first step of an operation chain?
e.g generate first N elements. Then add all these N elements.

Or should it apply to every step in an operation chain?
e.g Return the first N elements matching the given seeds then pass these N elements as the seeds of a second get Operations and limit the results of that operation to N.

Or should it apply to only the last step in an operation chain?
e.g Return all elements matching the given seeds then pass these elements as the seeds of a second get operation and return only N results of that operation.

Also investigate what to do when the result on an operation chain is void?

**Comment by p013570** [comment]
The limiting number could be added as a field to the operation class.

**Comment by p013570** [comment]
Merged into develop.

**Comment by p013570** [comment]
## Migration Steps
The query parameter 'n' has been removed from the rest api. Instead, each get operation now has a resultsLimit field - this allows each operation in a chain to be limited instead of just the final operation.
