### ISSUE TITLE
Crown copyright

### ISSUE THREAD

**Issue by pdm126** [GovernmentCommunicationsHeadquarters/Gaffer#6]
Some of your files have crown copyright on them then the apache2 licence UNDER it. Point two of the Apache licence is 2. Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.

It's hard to licence stuff. But these two points in some of your files are contradictory thus your code can't be used. Remove the crown copyright assertion. You only need the Apache in the top of the repo the rest is covered. Get a better lawyer, check your code before you publish. Consider changing to bsc or mit licence.

Very clean neat Java btw.

**Comment by emilv** [comment]
I believe you are wrong. They can very well claim copyright and then grant a copyright license. In fact, only the one who have copyright claims can grant a copyright license in the first place.

Have you even read the [Apache license](http://www.apache.org/licenses/LICENSE-2.0)? It claims right there in the [appendx](http://www.apache.org/licenses/LICENSE-2.0#apply) that this is the exact format to use!

**Comment by gaffer01** [comment]
We agree with the comment of @emilv but we are contacting the Apache Software Foundation to double check.

**Comment by pdm126** [comment]
Thanks, upon reflection and some asking around I believe you are both correct. I have worked with licenses before yes, just never seen the crown copyright then anything open source. I thought that crown copyright carried quite an extra significance to it. Thanks for being open enough to look into it.
