### ISSUE TITLE
0.31 RC1 BugFix

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#62]
Small Bug fixes for RC1 branch
Null Check for empty group in AbstractCoreKeyAccumuloElementConverter,
Remove maintenance jar building as part of the accumulo-store, it must be packages up elsewhere with the functions/serialisers
Adding null check for accumulo-store bulk import partitioner option.

**Comment by p013570** [comment]
Merged into release 0.3.1 branch
