### ISSUE TITLE
Custom Splits File path over-ridden in accumuloStore addElementsFromHdfs operation

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#68]
Currently you must set a splits file path on the addElementsFromHdfs operation, but it will be over-ridden with the store's default.

**Comment by p013570** [comment]
This issue will also address:

- Renaming constants files to package specific names to avoid import conflict
- Adding ability to use custom partitioner to addElementsFromhdfs operation

**Comment by p013570** [comment]
Merged into develop
