### ISSUE TITLE
Racism and sexism within this project (trigger warning)

### ISSUE THREAD

**Issue by installgen2** [GovernmentCommunicationsHeadquarters/Gaffer#7]
It has come to my attention that you have just closed multiple issues and pull requests, and this appears to have been done without checking your privilege, or for any people of colour, or women. It is very possible that these actions were a result of racism, sexism, or both. I recommend you find a long and detailed CoC and shove it right up inside this repository, to prevent any future discrimination that may be caused by your CIS white male privilege.

**Comment by GraspingControllingHurtingQuagmire** [comment]
Some excellent points raised by installgen2. I hope they can be rectified ASAP.

**Comment by GraspingControllingHurtingQuagmire** [comment]
P.S., project maintainers may find some useful reading attached.
[1984.txt](https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/files/65853/1984.txt)
