### ISSUE TITLE
Add Accumulostore SplitTable Operation.

### ISSUE THREAD

**Issue by james010101101** [GovernmentCommunicationsHeadquarters/Gaffer#76]
The accumulostore should have an operation to add split points to a table, 
These split points should be able to be generated by providing a directory of sample data, which will be used to create the splits.

In use this should be used as part of an operation chain when loading in data particularly for the first time, 
First split the table according to the data,
Then run the bulk import using then enable the accumulo partitioner option to use those new splits.

**Comment by p013570** [comment]
Merged into develop.
