### ISSUE TITLE
Error while running SimpleQuery.java

### ISSUE THREAD

**Issue by pranita-s** [GovernmentCommunicationsHeadquarters/Gaffer#77]
I am getting following error while running SimpleQuery.java

ubuntu@ip-172-31-24-17:~/Downloads/installs/accumulo-1.6.4$ bin/accumulo gaffer.example.SimpleQuery

Thread "gaffer.example.SimpleQuery" died Failed to create input stream from path: file:/home/ubuntu/Downloads/installs/accumulo-1.6.4/lib/ext/example-0.3.1-SNAPSHOT.jar!/dataSchema.json
java.lang.IllegalArgumentException: Failed to create input stream from path: file:/home/ubuntu/Downloads/installs/accumulo-1.6.4/lib/ext/example-0.3.1-SNAPSHOT.jar!/dataSchema.json
        at gaffer.graph.Graph.createInputStream(Graph.java:428)
        at gaffer.graph.Graph.<init>(Graph.java:138)
        at gaffer.graph.Graph.<init>(Graph.java:120)
        at gaffer.graph.Graph.<init>(Graph.java:83)
        at gaffer.example.SimpleQuery.run(SimpleQuery.java:93)
        at gaffer.example.SimpleQuery.main(SimpleQuery.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.accumulo.start.Main$1.run(Main.java:141)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: file:/home/ubuntu/Downloads/installs/accumulo-1.6.4/lib/ext/example-0.3.1-SNAPSHOT.jar!/dataSchema.json
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:317)
        at java.nio.file.Files.newByteChannel(Files.java:363)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:380)
        at java.nio.file.Files.newInputStream(Files.java:108)
        at gaffer.graph.Graph.createInputStream(Graph.java:426)
        ... 11 more

Following are the contents of .jar  file

ubuntu@ip-172-31-24-17:~/Downloads/installs/accumulo-1.6.4/lib/ext$ jar -tvf example-0.3.1-SNAPSHOT.jar
  0 Tue Feb 23 11:05:32 UTC 2016 META-INF/
   131 Tue Feb 23 11:05:30 UTC 2016 META-INF/MANIFEST.MF
     0 Tue Feb 23 10:51:06 UTC 2016 gaffer/
     0 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/
     0 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/
     0 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/impl/add/
     0 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/
     0 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/generate/
     0 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/
     0 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/generator/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/function/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/function/transform/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/schema/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/generator/
     0 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/serialiser/
     0 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/
     0 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/operation/
     0 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/operation/handler/
     0 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/
     0 Tue Feb 23 10:48:56 UTC 2016 gaffer/graph/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/
     0 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/exception/
  3269 Fri Feb 19 07:31:54 UTC 2016 addData.json
  1928 Fri Feb 19 07:31:54 UTC 2016 complexQuery.json
  1014 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/impl/add/AddElements.class
  2566 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/impl/add/AddElements$Builder.class
  2180 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/Validate$Builder.class
  1757 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetElements.class
  4990 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetElementsSeed$Builder.class
  2684 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEntitiesBySeed.class
  3193 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetRelatedEntities$Builder.class
  5044 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetRelatedElements$Builder.class
  2740 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetAdjacentEntitySeeds.class
  2833 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetRelatedElements.class
  2816 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetElementsSeed.class
  2678 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetRelatedEdges.class
  1079 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetElements$Builder.class
  3176 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEntitiesBySeed$Builder.class
   997 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEdges$Builder.class
  1023 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEntities$Builder.class
  4421 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetAdjacentEntitySeeds$Builder.class
  2654 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEdgesBySeed.class
  3148 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetRelatedEdges$Builder.class
  2986 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEntities.class
  2696 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetRelatedEntities.class
  2905 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEdges.class
  3675 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/get/GetEdgesBySeed$Builder.class
  3121 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/generate/GenerateObjects$Builder.class
  3441 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/generate/GenerateElements.class
  3005 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/generate/GenerateElements$Builder.class
  3108 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/generate/GenerateObjects.class
  2471 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/impl/Validate.class
  3219 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/OperationChain$Builder$TypedBuilder.class
   272 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/VoidInput.class
  4824 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/AbstractOperation.class
  1490 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/GetOperation$IncludeEdgeType.class
  1313 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/GetOperation$IncludeIncomingOutgoingType.class
  1490 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/OperationChain$Builder.class
   614 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/OperationException.class
  1612 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/GetOperation.class
  2207 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/AbstractOperation$Builder.class
  7355 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/AbstractGetOperation.class
  1948 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/AbstractValidatable$Builder.class
  4767 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/AbstractValidatable.class
   656 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/Validatable.class
  1185 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/GetOperation$SeedMatchingType.class
  1449 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/ElementSeed.class
  3075 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/EdgeSeed.class
  2368 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/EntitySeed.class
  3285 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/generator/EntitySeedExtractor.class
  2460 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/generator/EdgeSeedExtractor.class
  1723 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/data/ElementSeed$Matches.class
  2888 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/OperationChain$Builder$TypelessBuilder.class
   272 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/VoidOutput.class
  2667 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/OperationChain.class
   227 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/OperationChain$1.class
  4252 Tue Feb 23 10:45:00 UTC 2016 gaffer/operation/AbstractGetOperation$Builder.class
  1009 Tue Feb 23 10:44:58 UTC 2016 gaffer/operation/Operation.class
  5964 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/SimpleQuery.class
  8033 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/ComplexQuery.class
  1796 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/function/transform/StarRatingTransform.class
  1920 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/Review.class
   605 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/schema/Property.class
   418 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/schema/TransientProperty.class
   477 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/schema/Group.class
  1957 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/Viewing.class
  2948 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/SampleData.class
  2122 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/Film.class
  2101 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/Person.class
  1139 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/data/Certificate.class
  1929 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/generator/FilmGenerator.class
  3166 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/generator/DataGenerator.class
  2090 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/generator/ViewingGenerator.class
  2078 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/generator/ReviewGenerator.class
  1889 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/generator/PersonGenerator.class
  1919 Fri Feb 19 07:31:56 UTC 2016 gaffer/example/serialiser/CertificateVisibilitySerialiser.class
  1822 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/operation/handler/GenerateObjectsHandler.class
   464 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/operation/handler/OperationHandler.class
  1793 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/operation/handler/GenerateElementsHandler.class
  1558 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/operation/handler/ValidateHandler.class
 14948 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/Store.class
   707 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/StoreException.class
  3700 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/StoreProperties.class
  1441 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/StorePropertyDefinition$Builder.class
  5122 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/StoreSchema.class
  3308 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/StorePropertyDefinition.class
  3190 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/StoreSchema$Builder.class
  2910 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/StoreElementDefinition.class
  1200 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/schema/StoreElementDefinition$Builder.class
  1090 Tue Feb 23 10:51:06 UTC 2016 gaffer/store/StoreTrait.class
 10615 Tue Feb 23 10:48:56 UTC 2016 gaffer/graph/Graph.class
  2879 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/ElementValidator.class
  3314 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/TransformOneToManyIterable.class
  2065 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/ElementTuple.class
  3809 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/Entity.class
   766 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/Edge$1.class
   671 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/Entity$1.class
  3262 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/Properties.class
  4960 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/Edge.class
   283 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/ElementValueLoader.class
  2265 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/ElementAggregator$Builder.class
  2039 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/ElementAggregator.class
  2933 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/ElementTransformer$Builder.class
  1554 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/ElementFilter.class
  2490 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/ElementFilter$Builder.class
  1566 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/function/ElementTransformer.class
  3848 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/LazyEdge.class
  3129 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/ElementComponentKey.class
  3163 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/LazyEntity.class
  4394 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/Element.class
  1435 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/IdentifierType.class
  4758 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/LazyProperties.class
  1681 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/element/PropertiesTuple.class
  3132 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/TransformOneToManyIterable$1.class
  2460 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/ValidatedElements.class
   739 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/IsEdgeValidator.class
   234 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/Validator.class
  2677 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/TransformIterable$1.class
  1430 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/OneToManyElementGenerator$1.class
  2327 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/OneToOneElementGenerator.class
  1536 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/OneToOneElementGenerator$1.class
  1651 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/OneToManyElementGenerator.class
  1611 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/OneToOneElementGenerator$2.class
   947 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/generator/ElementGenerator.class
   367 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/ElementDefinition.class
  5592 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedElementDefinition.class
  2237 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/ElementDefinitions$Builder.class
   202 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypeStore.class
  2037 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedElementDefinition$Builder.class
  1494 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewEdgeDefinition.class
  3165 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewElementDefinition$Builder.class
  1097 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewEntityDefinition.class
  3888 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewEntityDefinition$Builder.class
  2975 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/View.class
  1324 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewElementDefinition.class
  2487 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/View$Builder.class
  4067 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewElementDefinitionValidator.class
  4146 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/view/ViewEdgeDefinition$Builder.class
  3702 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataEntityDefinition$Builder.class
  7046 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataElementDefinition.class
  3960 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataEdgeDefinition$Builder.class
  4057 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataElementDefinitionValidator.class
  2348 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataSchema$Builder.class
  1105 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataEntityDefinition.class
  1760 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataElementDefinition$Builder.class
  1502 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataEdgeDefinition.class
  6536 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/DataSchema.class
   672 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/schema/exception/SchemaException.class
  2075 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedEdgeDefinition$Builder.class
  1195 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedEntityDefinition$Builder.class
  1793 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedEdgeDefinition.class
  1396 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedEntityDefinition.class
  8212 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/TypedElementDefinitionValidator.class
  8827 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/ElementDefinitions.class
   399 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/Types.class
   422 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/ElementDefinitionWithIds.class
  2633 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/elementdefinition/Type.class
   659 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/AlwaysValid.class
   747 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/IsEntityValidator.class
  3191 Tue Feb 23 10:35:06 UTC 2016 gaffer/data/TransformIterable.class
  1255 Fri Feb 19 07:31:54 UTC 2016 store.properties
   518 Tue Feb 23 11:05:30 UTC 2016 trial.class
   900 Fri Feb 19 07:31:54 UTC 2016 storeSchema.json
  3467 Fri Feb 19 07:31:54 UTC 2016 dataSchema.json
   633 Fri Feb 19 07:31:54 UTC 2016 simpleQuery.json
     0 Tue Feb 23 11:05:32 UTC 2016 META-INF/maven/
     0 Tue Feb 23 11:05:32 UTC 2016 META-INF/maven/gaffer/
     0 Tue Feb 23 11:05:32 UTC 2016 META-INF/maven/gaffer/example/
  2591 Fri Feb 19 05:24:26 UTC 2016 META-INF/maven/gaffer/example/pom.xml
   107 Fri Feb 19 07:31:58 UTC 2016 META-INF/maven/gaffer/example/pom.properties

It can be seen that dataSchema.json is present at the correct location. I am not able to understand why the error is occurring.
Need help to resolve it !

**Comment by p013570** [comment]
Hi pranita-s,

Thank you for raising the issue, it has highlighted a problem with the way we were loading resources. The framework is still undergoing active development and we are now looking at loading the resources as streams instead of paths.

We have raised a ticket gh-78 to deal with the problem and are carrying out the work on branch G78-load-resources. We will get it merged into develop shortly and hopefully it will be included in release 0.3.2. Please feel free to check out this branch and confirm it resolves your issue.

**Comment by p013570** [comment]
Closing this issue as it has been fixed as part of issue gh-78 and has been included in release [0.3.2](https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/releases/tag/gaffer2-0.3.2).
