### ISSUE TITLE
Allow accumulo bulk import to be run in 2 steps

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#98]
The bulk import from HDFS for accumulo runs as 2 jobs: fetch from HDFS and import into accumulo.
If the second job fails it would be useful to be able to rerun the operation but skip the first step.

**Comment by a09631** [comment]
Pull request approved and merged into develop.

**Comment by james010101101** [comment]
# Migration steps

From now on when running a bulk import job, the provided failure directory must already be present, exist on the filesystem and the accumulo user must have read/write permissions on this folder.
